### ISSUE TITLE
Icon from Pi-hole

### ISSUE THREAD

**Issue by f0b04707** [tlk999/tingbot#1]
Nice app ! 

I see that you copied my Pi-hole tingapp as a base for your app but you forgot to remove the icon file (https://github.com/tlk999/tingbot/blob/master/sabnzb.tingapp/img/icon.png) :wink:

Cheers !

**Comment by tlk999** [comment]
Thanks for the heads up WhistleMaster, Have updated :)

Love the Pi-hole app to :D
